### ISSUE TITLE
[Suggestion] `tabled` Crate for Terminal Output

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/tabelle#1]
Hello, @wert007, and congrats for your new project!

I would like to suggest you the following crate as it focuses on writing tables formatted to the terminal:  https://github.com/zhiburt/tabled.  The license is MIT, so it would fit this project very well.  The idea would be to convert read input files to the `tabled` data structures in order to allow for mirroring the cells' formatting, like frame styles, bold formatting, or colours.  This might improve the user convenience regarding the output.

What do you think?

**Comment by wert007** [comment]
Hey!

It looks really fancy, but one thing I worry about, is that writing to your terminal is often slow. So we only re-render, what is necessary, since otherwise you will see flickering and similar things. With our custom table rendering this is no problem, but tabled does not seem to support big, often updating, tables on the terminal screen. Which is fine, I think it is a specific requirement of tabelle. But yes that would be a reason to not use tabled.

**Comment by kevinmatthes** [comment]
Okay!  I assumed that the output would be written to the terminal directly.
