### ISSUE TITLE
[Bug Report] Crash on Pycobertura Generated CSV

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/tabelle#2]
- Category:  major / the application does not fulfill the task it is designed for
- Steps to reproduce:
  1. cargo tarpaulin --engine llvm --out xml
  2. pycobertura show -f csv cobertura.xml > cobertura.csv
  3. cargo r -- cobertura.csv
- Detailed description:  Tarpaulin is a Rust binary to determine the code coverage of a project.  At option, it can also generate you some reports to be processed by further software.  Pycobertura is such software; I use to format the report for comments on PRs.  It can also convert the Tarpaulin XML report into other formats, like CSV, for instance.  I assumed your application would handle them, as well, because you stated this behaviour in your README.  Instead, the application crashes on an assertion and makes the terminal unusable, as well; normally, one could expect to enter further instructions in the same terminal instance but the crash also seems to affect the terminal process as a whole.  Hence, this is ***really*** a major bug you need to take care about.

**Comment by wert007** [comment]
Could you maybe send me such a csv file so I can debug it?

And yes, terminal displaying is still broken in a lot of points (flickering in certain situations, screens often not clearing, even though they should and could and similar things). So it is no surprise that such a crash happens. It would probably be nicer to add `thiserror` to `tabelle-core` and make the gui show a error message? At least as a first fix, so that no crashes happen.

I actually uploaded this repository to have it on another computer, but at the same time I actually think it could be something very useful, so that is why I made sure to add a README and polish the repository.

**Comment by kevinmatthes** [comment]
Here is the cobertura report for Aeruginous v2.0.0:

```
Filename;Stmts;Miss;Cover;Missing
src/application.rs;29;29;0.00%;87-137
src/cffreference.rs;68;0;100.00%;
src/macros.rs;4;0;100.00%;
src/running.rs;4;0;100.00%;
src/version.rs;26;0;100.00%;
src/pattern/buffer.rs;21;0;100.00%;
src/pattern/io_processor.rs;19;19;0.00%;72-160
src/pattern/reader.rs;31;20;35.48%;57-58, 75-79, 90-109, 123-139
src/pattern/writer.rs;77;30;61.04%;133-152, 187-197, 231-259
src/changelog/comment_changes.rs;163;163;0.00%;106-399
src/changelog/fragment.rs;11;0;100.00%;
src/graphing/agd.rs;156;0;100.00%;
src/graphing/graph.rs;146;0;100.00%;
src/traits/append_as_line.rs;9;0;100.00%;
src/traits/colour_message.rs;8;0;100.00%;
src/traits/convert_buffer.rs;21;0;100.00%;
src/traits/prefer.rs;3;0;100.00%;
src/traits/to_ron.rs;4;0;100.00%;
src/traits/to_stderr.rs;4;0;100.00%;
TOTAL;804;261;67.54%;
```

**Comment by wert007** [comment]
Okay, I know why it fails. `tabelle` parses csv files very simply by just splitting each line into rows and then splitting everything by a `,`. So it does not read this file correctly. I will see, that I fix that today.
